#!/usr/bin/env python3
"""Create a branch-oriented index for EMOTIC experiment artifacts.

The experiment scripts historically write to ``output/emotic_*`` directly.
Many evaluation/summarization programs depend on those exact paths, so this
tool does not move result directories.  Instead it builds a stable index under
``output/by_branch/<branch>/`` using symlinks and writes ``output/MANIFEST.md``.
Run it again after syncing new server results back to the local workspace.
"""

from __future__ import annotations

import argparse
import fnmatch
import os
from pathlib import Path


BRANCHES = {
    "emotic": {
        "title": "Baseline DDP / EMOTIC protocol",
        "patterns": [
            "emotic_b5c3_ddp_semantic_tau2*",
            "emotic_b5c3_sem_tau2_smoke",
            "emotic_upper_bound_ddp_semantic*",
        ],
    },
    "emotic-prototype-adapter": {
        "title": "External CLIP Prototype Adapter and score fusion",
        "patterns": [
            "emotic_clip_feature_cache",
            "emotic_prototype*",
        ],
    },
    "emotic-ddp-internal-adapter": {
        "title": "DDP internal shared feature adapter / CLS gate / final ablation",
        "patterns": [
            "emotic_adapter_final_ablation",
            "emotic_adapter_inference_benchmark",
            "emotic_ddp*",
        ],
    },
}


def classify(name: str) -> str | None:
    for branch, spec in BRANCHES.items():
        for pattern in spec["patterns"]:
            if fnmatch.fnmatch(name, pattern):
                return branch
    return None


def safe_symlink(target: Path, link: Path, dry_run: bool = False) -> None:
    if link.is_symlink() or link.exists():
        if link.is_symlink() and os.readlink(link) == os.path.relpath(target, link.parent):
            return
        if dry_run:
            print(f"replace {link} -> {target}")
            return
        if link.is_dir() and not link.is_symlink():
            raise RuntimeError(f"Refusing to replace real directory: {link}")
        link.unlink()
    rel_target = os.path.relpath(target, link.parent)
    if dry_run:
        print(f"ln -s {rel_target} {link}")
        return
    link.symlink_to(rel_target)


def write_manifest(output_root: Path, grouped: dict[str, list[Path]], unknown: list[Path]) -> None:
    lines: list[str] = [
        "# EMOTIC output artifact manifest",
        "",
        "This file is generated by `tools/organize_emotic_artifacts.py`.",
        "Result directories remain in their original `output/emotic_*` paths so existing evaluation scripts keep working.",
        "Use `output/by_branch/<branch>/` for a cleaner branch-oriented view.",
        "",
    ]
    for branch, spec in BRANCHES.items():
        lines.extend([f"## {branch}", "", spec["title"], ""])
        entries = grouped.get(branch, [])
        if not entries:
            lines.append("- No synced artifacts found.")
        else:
            for path in entries:
                lines.append(f"- `{path.name}/`")
        lines.append("")

    if unknown:
        lines.extend(["## Unclassified", ""])
        for path in unknown:
            lines.append(f"- `{path.name}/`")
        lines.append("")

    (output_root / "MANIFEST.md").write_text("\n".join(lines), encoding="utf-8")


def write_index_readme(output_root: Path) -> None:
    by_branch = output_root / "by_branch"
    lines = [
        "# Branch-oriented output index",
        "",
        "These directories contain symlinks to the original result folders one level above.",
        "The original paths are intentionally kept stable because scripts and summaries reference them directly.",
        "",
    ]
    for branch, spec in BRANCHES.items():
        lines.append(f"- `{branch}/`: {spec['title']}")
    lines.append("")
    (by_branch / "README.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-root", default="output")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    output_root = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)
    by_branch = output_root / "by_branch"
    if not args.dry_run:
        by_branch.mkdir(parents=True, exist_ok=True)

    grouped: dict[str, list[Path]] = {branch: [] for branch in BRANCHES}
    unknown: list[Path] = []

    for path in sorted(output_root.iterdir()):
        if path.name in {"by_branch", "MANIFEST.md"}:
            continue
        if not path.is_dir():
            continue
        branch = classify(path.name)
        if branch is None:
            unknown.append(path)
        else:
            grouped[branch].append(path)

    for branch in BRANCHES:
        branch_dir = by_branch / branch
        if not args.dry_run:
            branch_dir.mkdir(parents=True, exist_ok=True)
        for target in grouped[branch]:
            safe_symlink(target, branch_dir / target.name, dry_run=args.dry_run)

    if not args.dry_run:
        write_manifest(output_root, grouped, unknown)
        write_index_readme(output_root)

    print("Artifact index:")
    for branch in BRANCHES:
        print(f"  {branch}: {len(grouped[branch])} directories")
    if unknown:
        print(f"  unclassified: {len(unknown)} directories")
    print(f"Wrote {output_root / 'MANIFEST.md'} and {by_branch}/")


if __name__ == "__main__":
    main()
